"""Words I use for Task 3 queries and Task 4 plots (I filter to vocabulary at runtime)."""

from __future__ import annotations

# Task 3 cosine neighbor queries (assignment-style list).
QUERY_WORDS = ["research", "student", "phd", "exam"]

QUERY_ALIASES: dict[str, list[str]] = {
    "exam": ["examination", "exams", "mid-semester", "end-semester"],
}

# I encode analogies as (a, b, c) for A:B :: C:?.
ANALOGY_TRIPLETS: list[tuple[str, str, str]] = [
    ("ug", "btech", "pg"),
    ("undergraduate", "bachelor", "graduate"),
    ("faculty", "professor", "student"),
    ("course", "credit", "degree"),
    ("science", "engineering", "theory"),
]

# I keep this list large so PCA/t-SNE show several clusters after vocab filtering.
VIZ_WORDS = [
    "research",
    "student",
    "phd",
    "exam",
    "thesis",
    "dissertation",
    "course",
    "credit",
    "faculty",
    "professor",
    "science",
    "engineering",
    "undergraduate",
    "graduate",
    "bachelor",
    "master",
    "lecture",
    "laboratory",
    "theory",
    "practice",
    "development",
    "academic",
    "university",
    "college",
    "degree",
    "program",
    "seminar",
    "workshop",
    "department",
    "paper",
    "journal",
    "conference",
    "scholar",
    "candidate",
    "admission",
    "curriculum",
    "syllabus",
    "grade",
    "marks",
    "evaluation",
    "project",
    "internship",
    "hostel",
    "campus",
    "library",
    "laboratory",
    "technology",
    "computer",
    "software",
    "hardware",
    "mathematics",
    "physics",
    "chemistry",
    "biology",
    "electrical",
    "mechanical",
    "civil",
    "chemical",
    "materials",
    "design",
    "innovation",
    "discovery",
    "experiment",
    "analysis",
    "model",
    "system",
    "network",
    "database",
    "algorithm",
    "programming",
    "instruction",
    "teaching",
    "learning",
    "assessment",
    "assignment",
    "tutorial",
    "supervisor",
    "advisor",
    "mentor",
    "scholarship",
    "fellowship",
    "assistantship",
    "registration",
    "enrollment",
    "attendance",
    "examination",
    "semester",
    "trimester",
    "calendar",
    "schedule",
    "committee",
    "council",
    "senate",
    "regulation",
    "policy",
    "guideline",
    "handbook",
    "prospectus",
    "notification",
    "circular",
    "office",
    "director",
    "dean",
    "head",
    "chair",
    "coordinator",
    "administration",
    "finance",
    "accounts",
    "purchase",
    "infrastructure",
    "laboratory",
    "equipment",
    "facility",
]
